version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:14.18.0
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn
      - run:
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://www.vismix.co --delete
workflows:
  version: 2
  build:
    jobs:
      - build_project:
          filters:
              tags:
                only: /.*/
      - deploy_project:
          requires:
            - build_project
          context: aws-context
          filters:
            tags:
              only: /.*/